require 'docker'
require 'English'
require 'erb'
require 'fileutils'
require 'io/console'
require 'optparse'
require 'thor'
require 'tmpdir'

require_relative 'sle2docker/cli'
require_relative 'sle2docker/exceptions'
require_relative 'sle2docker/prebuilt_image'
require_relative 'sle2docker/version'
